services:
  tools:
    build:
      context: .
      dockerfile: ../../build/docker/go-tools/Dockerfile
    working_dir: /app/
    volumes:
      - ../../:/app/
    command: /bin/sh -c ''

  vet:
    extends:
      service: tools
    entrypoint: /bin/sh -c 'git config --global --add safe.directory /app && ./scripts/linting/run-vet.sh'

  fix-imports:
    extends:
      service: tools
    entrypoint: /bin/sh -c 'git config --global --add safe.directory /app && ./scripts/style/fix-imports.sh'

  fix-fmt:
    extends:
      service: tools
    entrypoint: /bin/sh -c 'git config --global --add safe.directory /app && ./scripts/style/fmt.sh'

  lint-full:
    extends:
      service: tools
    entrypoint: /bin/sh -c 'git config --global --add safe.directory /app && ./scripts/linting/run-linters.sh'

  go-generate:
    extends:
      service: tools
    entrypoint: /bin/sh -c 'git config --global --add safe.directory /app && ./scripts/codegen/go-generate.sh'
