{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to develo[...]",
    "title": "Strava API v3",
    "version": "3.0.0"
  },
  "host": "www.strava.com",
  "basePath": "/api/v3",
  "paths": {
    "/activities": {
      "post": {
        "description": "Creates a manual activity for an athlete, requires activity:write scope.",
        "tags": [
          "Activities"
        ],
        "summary": "Create an Activity",
        "operationId": "createActivity"
      }
    },
    "/activities/{id}": {
      "get": {
        "description": "Returns the given activity that is owned by the authenticated athlete. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "tags": [
          "Activities"
        ],
        "summary": "Get Activity",
        "operationId": "getActivityById"
      },
      "put": {
        "description": "Updates the given activity that is owned by the authenticated athlete. Requires activity:write. Also requires activity:read_all in order to update Only Me activities",
        "tags": [
          "Activities"
        ],
        "summary": "Update Activity",
        "operationId": "updateActivityById"
      }
    },
    "/activities/{id}/comments": {
      "get": {
        "description": "Returns the comments on the given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "tags": [
          "Activities"
        ],
        "summary": "List Activity Comments",
        "operationId": "getCommentsByActivityId"
      }
    },
    "/activities/{id}/kudos": {
      "get": {
        "description": "Returns the athletes who kudoed an activity identified by an identifier. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "tags": [
          "Activities"
        ],
        "summary": "List Activity Kudoers",
        "operationId": "getKudoersByActivityId"
      }
    },
    "/activities/{id}/laps": {
      "get": {
        "description": "Returns the laps of an activity identified by an identifier. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "tags": [
          "Activities"
        ],
        "summary": "List Activity Laps",
        "operationId": "getLapsByActivityId"
      }
    },
    "/activities/{id}/streams": {
      "get": {
        "description": "Returns the given activity's streams. Requires activity:read scope. Requires activity:read_all scope for Only Me activities.",
        "tags": [
          "Streams"
        ],
        "summary": "Get Activity Streams",
        "operationId": "getActivityStreams"
      }
    },
    "/activities/{id}/zones": {
      "get": {
        "description": "Summit Feature. Returns the zones of a given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "tags": [
          "Activities"
        ],
        "summary": "Get Activity Zones",
        "operationId": "getZonesByActivityId"
      }
    },
    "/athlete": {
      "get": {
        "description": "Returns the currently authenticated athlete. Tokens with profile:read_all scope will receive a detailed athlete representation; all others will receive a summary representation.",
        "tags": [
          "Athletes"
        ],
        "summary": "Get Authenticated Athlete",
        "operationId": "getLoggedInAthlete"
      },
      "put": {
        "description": "Update the currently authenticated athlete. Requires profile:write scope.",
        "tags": [
          "Athletes"
        ],
        "summary": "Update Athlete",
        "operationId": "updateLoggedInAthlete"
      }
    },
    "/athlete/activities": {
      "get": {
        "description": "Returns the activities of an athlete for a specific identifier. Requires activity:read. Only Me activities will be filtered out unless requested by a token with activity:read_all.",
        "tags": [
          "Activities"
        ],
        "summary": "List Athlete Activities",
        "operationId": "getLoggedInAthleteActivities"
      }
    },
    "/athlete/clubs": {
      "get": {
        "description": "Returns a list of the clubs whose membership includes the authenticated athlete.",
        "tags": [
          "Clubs"
        ],
        "summary": "List Athlete Clubs",
        "operationId": "getLoggedInAthleteClubs"
      }
    },
    "/athlete/zones": {
      "get": {
        "description": "Returns the the authenticated athlete's heart rate and power zones. Requires profile:read_all.",
        "tags": [
          "Athletes"
        ],
        "summary": "Get Zones",
        "operationId": "getLoggedInAthleteZones"
      }
    },
    "/athletes/{id}/routes": {
      "get": {
        "description": "Returns a list of the routes created by the authenticated athlete. Private routes are filtered out unless requested by a token with read_all scope.",
        "tags": [
          "Routes"
        ],
        "summary": "List Athlete Routes",
        "operationId": "getRoutesByAthleteId"
      }
    },
    "/athletes/{id}/stats": {
      "get": {
        "description": "Returns the activity stats of an athlete. Only includes data from activities set to Everyone visibilty.",
        "tags": [
          "Athletes"
        ],
        "summary": "Get Athlete Stats",
        "operationId": "getStats"
      }
    },
    "/clubs/{id}": {
      "get": {
        "description": "Returns a given a club using its identifier.",
        "tags": [
          "Clubs"
        ],
        "summary": "Get Club",
        "operationId": "getClubById"
      }
    },
    "/clubs/{id}/activities": {
      "get": {
        "description": "Retrieve recent activities from members of a specific club. The authenticated athlete must belong to the requested club in order to hit this endpoint. Pagination is supported. Athlete profile visibility is respected for all activities.",
        "tags": [
          "Clubs"
        ],
        "summary": "List Club Activities",
        "operationId": "getClubActivitiesById"
      }
    },
    "/clubs/{id}/admins": {
      "get": {
        "description": "Returns a list of the administrators of a given club.",
        "tags": [
          "Clubs"
        ],
        "summary": "List Club Administrators",
        "operationId": "getClubAdminsById"
      }
    },
    "/clubs/{id}/members": {
      "get": {
        "description": "Returns a list of the athletes who are members of a given club.",
        "tags": [
          "Clubs"
        ],
        "summary": "List Club Members",
        "operationId": "getClubMembersById"
      }
    },
    "/gear/{id}": {
      "get": {
        "description": "Returns an equipment using its identifier.",
        "tags": [
          "Gears"
        ],
        "summary": "Get Equipment",
        "operationId": "getGearById"
      }
    },
    "/routes/{id}": {
      "get": {
        "description": "Returns a route using its identifier. Requires read_all scope for private routes.",
        "tags": [
          "Routes"
        ],
        "summary": "Get Route",
        "operationId": "getRouteById"
      }
    },
    "/routes/{id}/export_gpx": {
      "get": {
        "description": "Returns a GPX file of the route. Requires read_all scope for private routes.",
        "tags": [
          "Routes"
        ],
        "summary": "Export Route GPX",
        "operationId": "getRouteAsGPX"
      }
    },
    "/routes/{id}/export_tcx": {
      "get": {
        "description": "Returns a TCX file of the route. Requires read_all scope for private routes.",
        "tags": [
          "Routes"
        ],
        "summary": "Export Route TCX",
        "operationId": "getRouteAsTCX"
      }
    },
    "/routes/{id}/streams": {
      "get": {
        "description": "Returns the given route's streams. Requires read_all scope for private routes.",
        "tags": [
          "Streams"
        ],
        "summary": "Get Route Streams",
        "operationId": "getRouteStreams"
      }
    },
    "/segment_efforts": {
      "get": {
        "description": "Returns a set of the authenticated athlete's segment efforts for a given segment.  Requires subscription.",
        "tags": [
          "SegmentEfforts"
        ],
        "summary": "List Segment Efforts",
        "operationId": "getEffortsBySegmentId"
      }
    },
    "/segment_efforts/{id}": {
      "get": {
        "description": "Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.",
        "tags": [
          "SegmentEfforts"
        ],
        "summary": "Get Segment Effort",
        "operationId": "getSegmentEffortById"
      }
    },
    "/segment_efforts/{id}/streams": {
      "get": {
        "description": "Returns a set of streams for a segment effort completed by the authenticated athlete. Requires read_all scope.",
        "tags": [
          "Streams"
        ],
        "summary": "Get Segment Effort Streams",
        "operationId": "getSegmentEffortStreams"
      }
    },
    "/segments/explore": {
      "get": {
        "description": "Returns the top 10 segments matching a specified query.",
        "tags": [
          "Segments"
        ],
        "summary": "Explore segments",
        "operationId": "exploreSegments"
      }
    },
    "/segments/starred": {
      "get": {
        "description": "List of the authenticated athlete's starred segments. Private segments are filtered out unless requested by a token with read_all scope.",
        "tags": [
          "Segments"
        ],
        "summary": "List Starred Segments",
        "operationId": "getLoggedInAthleteStarredSegments"
      }
    },
    "/segments/{id}": {
      "get": {
        "description": "Returns the specified segment. read_all scope required in order to retrieve athlete-specific segment information, or to retrieve private segments.",
        "tags": [
          "Segments"
        ],
        "summary": "Get Segment",
        "operationId": "getSegmentById"
      }
    },
    "/segments/{id}/starred": {
      "put": {
        "description": "Stars/Unstars the given segment for the authenticated athlete. Requires profile:write scope.",
        "tags": [
          "Segments"
        ],
        "summary": "Star Segment",
        "operationId": "starSegment"
      }
    },
    "/segments/{id}/streams": {
      "get": {
        "description": "Returns the given segment's streams. Requires read_all scope for private segments.",
        "tags": [
          "Streams"
        ],
        "summary": "Get Segment Streams",
        "operationId": "getSegmentStreams"
      }
    },
    "/uploads": {
      "post": {
        "description": "Uploads a new data file to create an activity from. Requires activity:write scope.",
        "tags": [
          "Uploads"
        ],
        "summary": "Upload Activity",
        "operationId": "createUpload"
      }
    },
    "/uploads/{uploadId}": {
      "get": {
        "description": "Returns an upload for a given identifier. Requires activity:write scope.",
        "tags": [
          "Uploads"
        ],
        "summary": "Get Upload",
        "operationId": "getUploadById"
      }
    }
  },
  "securityDefinitions": {
    "strava_oauth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://www.strava.com/api/v3/oauth/authorize",
      "tokenUrl": "https://www.strava.com/api/v3/oauth/token",
      "scopes": {
        "activity:read": "Read the user's activity data for activities that are visible to Everyone and Followers, excluding privacy zone data",
        "activity:read_all": "The same access as activity:read, plus privacy zone data and access to read the user's activities with visibility set to Only You",
        "activity:write": "Access to create manual activities and uploads, and access to edit any activities that are visible to the app, based on activity read access level",
        "profile:read_all": "Read all profile information even if the user has set their profile visibility to Followers or Only You",
        "profile:write": "Update the user's weight and Functional Threshold Power (FTP), and access to star or unstar segments on their behalf",
        "read": "Read public segments, public routes, public profile data, public posts, public events, club feeds, and leaderboards",
        "read_all": "Read private routes, private segments, and private events for the user"
      }
    }
  },
  "security": [
    {
      "strava_oauth": [
        "public"
      ]
    }
  ]
}